/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SpecialCallouts
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_STANDARD_COLORS = {
  red: "#e74c3c",
  blue: "#3498db",
  green: "#2ecc71",
  yellow: "#f1c40f",
  orange: "#e67e22",
  purple: "#9b59b6",
  pink: "#e84393",
  teal: "#1abc9c",
  grey: "#95a5a6",
  gray: "#95a5a6"
};
var DEFAULT_SETTINGS = {
  customColors: [],
  standardColors: { ...DEFAULT_STANDARD_COLORS },
  customStyles: []
};
function debounce(func, wait) {
  let timeout = null;
  return (...args) => {
    if (timeout) clearTimeout(timeout);
    timeout = setTimeout(() => func(...args), wait);
  };
}
function isValidHex(hex) {
  return /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/.test(hex);
}
function normalizeHex(hex) {
  if (!hex.startsWith("#")) hex = "#" + hex;
  if (hex.length === 4) {
    hex = "#" + hex[1] + hex[1] + hex[2] + hex[2] + hex[3] + hex[3];
  }
  return hex.toUpperCase();
}
var SpecialCallouts = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.observers = /* @__PURE__ */ new Map();
    this.processedElements = /* @__PURE__ */ new WeakMap();
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SpecialCalloutsSettingTab(this.app, this));
    this.debouncedColumnApply = debounce((container, colCount) => {
      this.applyColumnsToContainer(container, colCount);
    }, 50);
    this.registerMarkdownPostProcessor((element) => {
      const callouts = element.querySelectorAll(".callout");
      callouts.forEach((callout) => this.processCallout(callout));
    });
  }
  processCallout(calloutEl) {
    const titleEl = calloutEl.querySelector(".callout-title");
    if (!titleEl) return;
    const innerTitleEl = titleEl.querySelector(".callout-title-inner") || titleEl;
    const fullText = innerTitleEl.textContent || "";
    const cacheKey = `${calloutEl.getAttribute("data-callout")}_${fullText}`;
    if (this.processedElements.get(calloutEl) === cacheKey) return;
    this.processedElements.set(calloutEl, cacheKey);
    const calloutType = calloutEl.getAttribute("data-callout");
    const typeStyle = this.settings.customStyles.find((s) => s.name.toLowerCase() === (calloutType == null ? void 0 : calloutType.toLowerCase()));
    if (typeStyle) this.applyStyleObject(calloutEl, typeStyle);
    const metadataRegex = /^\s*\(([^\)]+)\)/;
    const match = fullText.match(metadataRegex);
    if (match) {
      const content = match[1];
      const processedTitle = fullText.replace(match[0], "").trim();
      if (innerTitleEl.textContent !== processedTitle) innerTitleEl.textContent = processedTitle;
      let params = [];
      let layoutParam = null;
      const layoutRegex = /(?:^|[\s,])(\d+(?:[:,\/]\d+){1,2})(?:$|[\s,])/;
      const layoutMatch = content.match(layoutRegex);
      let remainingContent = content;
      if (layoutMatch) {
        layoutParam = layoutMatch[1];
        remainingContent = remainingContent.replace(layoutParam, "").replace(/,,/g, ",");
      }
      params = remainingContent.split(",").map((p) => p.trim()).filter((p) => p.length > 0);
      if (layoutParam) params.push(layoutParam.trim());
      const styleParam = params.find((p) => p.toLowerCase().startsWith("style:"));
      if (styleParam) {
        const styleName = styleParam.split(":")[1].trim().toLowerCase();
        const manualStyle = this.settings.customStyles.find((s) => s.name.toLowerCase() === styleName);
        if (manualStyle) this.applyStyleObject(calloutEl, manualStyle);
      }
      let targetColCount = null;
      params.forEach((pair) => {
        let key = "", rawValue = "";
        const subplotMatch = pair.match(/^(\d+)[:,\/](\d+)(?:[:,\/](\d+))?$/);
        if (subplotMatch) {
          const cols = parseInt(subplotMatch[2]);
          if (cols > 0) {
            const gap = 10;
            const widthCalc = `calc((100% - ${(cols - 1) * gap}px) / ${cols})`;
            calloutEl.style.flex = `0 0 ${widthCalc}`;
            calloutEl.style.width = widthCalc;
            calloutEl.style.maxWidth = widthCalc;
            calloutEl.style.setProperty("margin", "0", "important");
          }
          return;
        }
        if (pair.includes(":")) {
          const parts = pair.split(":");
          key = parts[0].trim().toLowerCase();
          rawValue = parts[1].trim();
        } else {
          return;
        }
        const resolveColor = (val) => {
          const std = this.settings.standardColors[val.toLowerCase()];
          if (std) return std;
          const cst = this.settings.customColors.find((c) => c.name.toLowerCase() === val.toLowerCase());
          return cst ? cst.hex : val;
        };
        if (key === "col" || key === "column") {
          const col = parseInt(rawValue);
          if (!isNaN(col)) targetColCount = col;
        } else if (["bg", "background", "color"].includes(key)) {
          this.applyColor(calloutEl, resolveColor(rawValue));
        } else if (["font", "text"].includes(key)) {
          this.applyTextColor(calloutEl, resolveColor(rawValue));
        } else if (["link", "a"].includes(key)) {
          this.applyLinkColor(calloutEl, resolveColor(rawValue));
        } else if (key === "icon") {
          this.applyIcon(calloutEl, rawValue);
        } else if (key === "glow") {
          const glow = parseInt(rawValue);
          if (!isNaN(glow)) {
            calloutEl.style.boxShadow = `0 0 ${glow * 2}px ${glow}px var(--callout-color)`;
            calloutEl.style.zIndex = "1";
          }
        } else if (key === "gradient") {
          const colors = rawValue.split("-");
          if (colors.length === 2) {
            const c1 = resolveColor(colors[0]);
            const c2 = resolveColor(colors[1]);
            calloutEl.style.background = `linear-gradient(90deg, ${c1}, ${c2})`;
            calloutEl.style.border = "none";
            calloutEl.style.color = "white";
          }
        } else if (key === "radius") {
          calloutEl.style.borderRadius = rawValue + "px";
        } else if (key === "border-width") {
          calloutEl.style.borderWidth = rawValue + "px";
        }
      });
      if (targetColCount !== null) {
        calloutEl.setAttribute("data-col", targetColCount.toString());
        calloutEl.style.setProperty("--smart-list-cols", targetColCount.toString());
        this.applyColumnsToContainer(calloutEl, targetColCount);
        this.setupObserver(calloutEl, targetColCount);
      }
    }
  }
  applyStyleObject(calloutEl, style) {
    this.applyColor(calloutEl, style.bg, style.border);
    this.applyTextColor(calloutEl, style.text);
    this.applyLinkColor(calloutEl, style.link);
    this.applyIcon(calloutEl, style.icon);
  }
  applyColor(callout, color, borderColor) {
    callout.style.setProperty("--callout-color", color);
    callout.style.borderLeftColor = color;
    callout.style.background = "";
    callout.style.backgroundColor = `color-mix(in srgb, ${color} 10%, transparent)`;
    if (borderColor) {
      callout.style.border = `1px solid ${borderColor}`;
      callout.style.borderLeft = `5px solid ${color}`;
    }
    const title = callout.querySelector(".callout-title");
    if (title) title.style.color = color;
    const icon = callout.querySelector(".callout-icon");
    if (icon) icon.style.color = color;
  }
  applyTextColor(callout, color) {
    const content = callout.querySelector(".callout-content");
    if (content) content.style.color = color;
  }
  applyLinkColor(callout, color) {
    callout.setAttribute("data-link-color", color);
    callout.style.setProperty("--link-color", color);
  }
  applyIcon(callout, iconName) {
    const iconEl = callout.querySelector(".callout-icon");
    if (iconEl && iconName) {
      iconEl.empty();
      (0, import_obsidian.setIcon)(iconEl, iconName);
    }
  }
  applyColumnsToContainer(container, colCount) {
    requestAnimationFrame(() => {
      const contentEl = container.querySelector(".callout-content");
      if (!contentEl) return;
      const lists = contentEl.querySelectorAll("ul, ol, .dataview.list-view-ul, .dataview-result-list-ul");
      lists.forEach((list) => {
        const listEl = list;
        listEl.style.columnCount = colCount.toString();
        listEl.style.columnGap = "2em";
        listEl.style.columnFill = "balance";
        listEl.style.width = "100%";
        listEl.querySelectorAll("li").forEach((li) => {
          li.style.breakInside = "avoid";
          li.style.pageBreakInside = "avoid";
        });
      });
    });
  }
  setupObserver(calloutEl, colCount) {
    var _a;
    if (this.observers.has(calloutEl)) (_a = this.observers.get(calloutEl)) == null ? void 0 : _a.disconnect();
    const contentEl = calloutEl.querySelector(".callout-content");
    if (!contentEl) return;
    const observer = new MutationObserver((mutations) => {
      let update = false;
      mutations.forEach((m) => m.addedNodes.forEach((n) => {
        if (n.nodeType === 1 && (n.matches("ul,ol,.dataview") || n.querySelector("ul,ol,.dataview"))) update = true;
      }));
      if (update) this.debouncedColumnApply(calloutEl, colCount);
    });
    observer.observe(contentEl, { childList: true, subtree: true });
    this.observers.set(calloutEl, observer);
  }
  onunload() {
    this.observers.forEach((o) => o.disconnect());
    this.observers.clear();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SpecialCalloutsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.tempName = "";
    this.tempIcon = "pencil";
    this.tempBg = "#3498db";
    this.tempBorder = "#3498db";
    this.tempText = "#ffffff";
    this.tempLink = "#dfe4ea";
    this.newCustomColorName = "";
    this.newCustomColorHex = "#ffffff";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "Special Callouts" });
    const standardSection = containerEl.createEl("details");
    standardSection.open = false;
    standardSection.createEl("summary", { text: "Standard Colors" });
    const standardDesc = standardSection.createEl("p");
    standardDesc.style.fontSize = "12px";
    standardDesc.style.color = "var(--text-muted)";
    standardDesc.setText("Edit the hex values for built-in color names.");
    Object.keys(this.plugin.settings.standardColors).forEach((colorName) => {
      if (colorName === "gray") return;
      new import_obsidian.Setting(standardSection).setName(colorName.charAt(0).toUpperCase() + colorName.slice(1)).addText((t) => {
        t.setValue(this.plugin.settings.standardColors[colorName]).onChange(async (v) => {
          if (isValidHex(v)) {
            this.plugin.settings.standardColors[colorName] = normalizeHex(v);
            if (colorName === "grey") this.plugin.settings.standardColors["gray"] = normalizeHex(v);
            await this.plugin.saveSettings();
          }
        });
      }).addColorPicker((c) => {
        c.setValue(this.plugin.settings.standardColors[colorName]).onChange(async (v) => {
          this.plugin.settings.standardColors[colorName] = v.toUpperCase();
          if (colorName === "grey") this.plugin.settings.standardColors["gray"] = v.toUpperCase();
          await this.plugin.saveSettings();
          this.display();
        });
      });
    });
    const customColorSection = containerEl.createEl("details");
    customColorSection.open = false;
    customColorSection.createEl("summary", { text: "Custom Colors" });
    const addColorRow = customColorSection.createDiv();
    addColorRow.style.display = "flex";
    addColorRow.style.gap = "10px";
    addColorRow.style.alignItems = "center";
    addColorRow.style.marginTop = "10px";
    const nameInput = addColorRow.createEl("input", { type: "text", placeholder: "name" });
    const hexInput = addColorRow.createEl("input", { type: "text", placeholder: "#HEX" });
    const pickerInput = addColorRow.createEl("input", { type: "color" });
    nameInput.addEventListener("input", (e) => this.newCustomColorName = e.target.value);
    hexInput.addEventListener("input", (e) => {
      let v = e.target.value;
      if (!v.startsWith("#")) v = "#" + v;
      if (isValidHex(v)) {
        this.newCustomColorHex = normalizeHex(v);
        pickerInput.value = this.newCustomColorHex;
      }
    });
    pickerInput.addEventListener("input", (e) => {
      this.newCustomColorHex = e.target.value;
      hexInput.value = this.newCustomColorHex.toUpperCase();
    });
    const addBtn = addColorRow.createEl("button", { text: "Add" });
    addBtn.onclick = async () => {
      if (this.newCustomColorName && isValidHex(this.newCustomColorHex)) {
        this.plugin.settings.customColors.push({ name: this.newCustomColorName, hex: this.newCustomColorHex });
        await this.plugin.saveSettings();
        this.display();
      }
    };
    this.plugin.settings.customColors.forEach((c, i) => {
      new import_obsidian.Setting(customColorSection).setName(c.name).setDesc(c.hex).addExtraButton((b) => b.setIcon("trash").onClick(async () => {
        this.plugin.settings.customColors.splice(i, 1);
        await this.plugin.saveSettings();
        this.display();
      }));
    });
    const styleSection = containerEl.createEl("details");
    styleSection.open = true;
    styleSection.createEl("summary", { text: "Custom Callout Styles" });
    const creatorCard = styleSection.createDiv();
    creatorCard.style.padding = "15px";
    creatorCard.style.border = "1px solid var(--background-modifier-border)";
    creatorCard.style.borderRadius = "8px";
    creatorCard.style.marginTop = "10px";
    new import_obsidian.Setting(creatorCard).setName("Name").addText((t) => t.setPlaceholder("project").setValue(this.tempName).onChange((v) => {
      this.tempName = v;
      this.updatePreview(previewBox);
    }));
    new import_obsidian.Setting(creatorCard).setName("Icon").addText((t) => t.setPlaceholder("zap").setValue(this.tempIcon).onChange((v) => {
      this.tempIcon = v;
      this.updatePreview(previewBox);
    }));
    const colorsDiv = creatorCard.createDiv();
    colorsDiv.style.display = "grid";
    colorsDiv.style.gridTemplateColumns = "1fr 1fr";
    colorsDiv.style.gap = "10px";
    const addColor = (name, val, cb) => {
      const d = colorsDiv.createDiv();
      new import_obsidian.Setting(d).setName(name).addColorPicker((c) => c.setValue(val).onChange((v) => {
        cb(v);
        this.updatePreview(previewBox);
      }));
    };
    addColor("Background", this.tempBg, (v) => this.tempBg = v);
    addColor("Border", this.tempBorder, (v) => this.tempBorder = v);
    addColor("Text", this.tempText, (v) => this.tempText = v);
    addColor("Link", this.tempLink, (v) => this.tempLink = v);
    const previewBox = creatorCard.createDiv({ cls: "callout" });
    previewBox.style.marginTop = "15px";
    this.updatePreview(previewBox);
    new import_obsidian.Setting(creatorCard).addButton((b) => b.setButtonText("Save Style").setCta().onClick(async () => {
      if (this.tempName) {
        this.plugin.settings.customStyles.push({
          name: this.tempName,
          bg: this.tempBg,
          border: this.tempBorder,
          text: this.tempText,
          link: this.tempLink,
          icon: this.tempIcon
        });
        await this.plugin.saveSettings();
        this.display();
      }
    }));
    if (this.plugin.settings.customStyles.length > 0) {
      const savedHeader = styleSection.createEl("h4", { text: "Saved Styles" });
      savedHeader.style.marginTop = "20px";
      this.plugin.settings.customStyles.forEach((s, i) => {
        new import_obsidian.Setting(styleSection).setName(s.name).setDesc(`Icon: ${s.icon}`).addExtraButton((b) => b.setIcon("trash").onClick(async () => {
          this.plugin.settings.customStyles.splice(i, 1);
          await this.plugin.saveSettings();
          this.display();
        }));
      });
    }
  }
  updatePreview(el) {
    el.empty();
    el.style.setProperty("--callout-color", this.tempBg);
    el.style.backgroundColor = `color-mix(in srgb, ${this.tempBg} 10%, transparent)`;
    el.style.border = `1px solid ${this.tempBorder}`;
    el.style.borderLeft = `5px solid ${this.tempBg}`;
    el.style.padding = "10px";
    const t = el.createDiv({ cls: "callout-title" });
    t.style.color = this.tempBg;
    const i = t.createDiv({ cls: "callout-icon" });
    (0, import_obsidian.setIcon)(i, this.tempIcon || "box");
    t.createDiv({ cls: "callout-title-inner", text: this.tempName || "Preview" });
  }
};
